/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:316238:
  appc.background(230);
} //_CODE_:window1:316238:

public void startClick(GButton source, GEvent event) { //_CODE_:startButton:993239:
  println("startButton - GButton >> GEvent." + event + " @ " + millis());
  // Pause resume function
  running = !running;
  if(running) {
    startButton.setText("Stop");
    loop();
  } else {
    startButton.setText("Start");
  }
} //_CODE_:startButton:993239:

public void chooseLayout(GDropList source, GEvent event) { //_CODE_:whichLayout:453337:
  println("Choose_Layout - GDropList >> GEvent." + event + " @ " + millis());
  whichFile = whichLayout.getSelectedText();
  setLayout();
} //_CODE_:whichLayout:453337:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 240, 120, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw1");
  startButton = new GButton(window1, 40, 30, 80, 30);
  startButton.setText("Start");
  startButton.addEventHandler(this, "startClick");
  whichLayout = new GDropList(window1, 130, 40, 90, 80, 3, 10);
  whichLayout.setItems(loadStrings("list_453337"), 0);
  whichLayout.addEventHandler(this, "chooseLayout");
  label1 = new GLabel(window1, 130, 20, 80, 20);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Choose file");
  label1.setOpaque(false);
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GButton startButton; 
GDropList whichLayout; 
GLabel label1; 
